### ISSUE TITLE
Security Vulnerability in Dependencies: Update Needed to Address Critical Issues

### ISSUE THREAD

**Issue by EilidhMc** [rbmh-partner-projects/custom-template-wizard#32]
**Overview**
We have encountered critical security vulnerabilities in our dream day project associated with the dependencies used by `custom-template-wizard`. After a bit of searching it appears the vulnerabilities are introduced through outdated packages in `custom-template-wizard`.

**Identified Vulnerabilities:**
- The `formidable` package used by `superagent`, which is a dependency of `chai-http`, was found to have critical severity vulnerabilities related to arbitrary file upload. More details can be found here: (https://github.com/advisories/GHSA-8cp3-66vr-3r4c).

**Steps to Reproduce:**
1. Clone the repository.
2. Run `npm install`.
3. Run `npm audit` to observe the reported vulnerabilities.

**Comment by andrekat** [comment]
Hey @EilidhMc,

Thanks again for reporting this issue. Once the PR is merged, please make sure to update the dependencies in your repository (especially the one linked to this repository -> custom-template-wizard). 

Best,
Andre
